<?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
        <meta http-equiv="content-type" content="text/html charset=utf-8" />
        <meta name="author" content="Graham Stark" />
        <meta name="keywords" content="Microsimulation, Legal Aid, Scotland" />
        <meta name="description" content="Simulation Models of Scottish Legal Aid System" />
        <meta name="robots" content="all" />
        <link rel="schema.DC" href="http://purl.org/dc/elements/1.1/" />

        <link rel="schema.DCTERMS" href="http://purl.org/dc/terms/" />
        <meta name="DC.description" xml:lang="en" content="Simulation Model NI Legal Aid System" />
        <meta name='DC.title' content='SMOSLAS Simulation Model Of Scottish Legal Aid System' />
        <meta name="DC.subject"  content="Microsimulation" />
 
        <meta name="DC.contributor"  content="Graham Stark" />
        <meta name="DC.type"  content="Interactive Resource" />
        <meta name="DC.type"  content="Software" />
        <link type="text/css" href="/slab/css/vw.css" rel="stylesheet"/>
        <link type="text/css" href="/slab/css/tables.css" rel="stylesheet"/>

        <title>@_$1_@</title>
        <script type="text/javascript" src="/slab/js/gksfunctions.js">        </script>
</head>
