 <table width='90%' cellpadding='10'>
 <tr><td width='20%'></td><td width='50%'>
 <table>
         <tr>
                <td><input type='submit' name="action" value='save' /></td>
                <td><input type='submit' name="action" value='run' /></td>
                <td><input type='submit' name="action" value='english' /></td>
                <!--
                <td><input type='submit' name="action" value='optimise' /></td>
                -->
                <td><input type='submit' name="action" value='reset' /></td>
                <td><input type='submit' name="action" value='uprate' /></td>
                <td>uprate amount (%) @_uprate-amount_@</td>
        </tr>
        </table>
</td>
<td width='20%'></td>
</tr>
</table>
