"
" 
" vim script to clean up tony's takeup spreadsheet files by subsituting all non non-numeric data
" use like: use like vim -e [file] < m2pas.vim

:set ignorecase

%s/lowerLimit/lower_limit/g
%s/upperLimit/upper_limit/g
%s/singlePersonsHousingCostsMax/single_persons_housing_costs_max/g
%s/partnersAllowance/partners_allowance/g
%s/otherDependantsAllowance/other_dependants_allowance/g
%s/numChildAgeLimits/num_child_age_limits/g
%s/childAgeLimit/child_age_limit/g
%s/childAllowance/child_allowance/g
%s/dependentAllowance/dependent_allowance/g
%s/dependentAllowances/dependent_allowances/g
%s/isFlat/is_flat/g
%s/waterRates/water_rates/g
%s/groundRent/ground_rent/g
%s/serviceCharge/service_charge/g
%s/repairsAndInsurance/repairs_and_insurance/g
%s/rentRebates/rent_rebates/g
%s/rateRebates/council_tax_rebates/g
%s/contType/cont_type/g
%s/contributionProportion/contribution_proportion/g
%s/contributionBand/contribution_band/g
%s/reformNumber/reform_number/g
%s/passportBenefits/passport_benefits/g
%s/useOwnIncomeTest/use_own_income_test/g
%s/incomeToUse/income_to_use/g
%s/lowerLimit/lower_limit/g
%s/upperLimit/upper_limit/g
%s/allowableExpenses/allowable_expenses/g
%s/allowableFinance/allowable_finance/g
%s/pensionerAgeLimit/pensioner_age_limit/g
%s/capitalDisregard/capital_disregard/g
%s/studentGrantDisregard/student_grant_disregard/g
%s/mortgageMaximum/mortgage_maximum/g
%s/averageWaterRates/average_water_rates/g
%s/businessProfitsProjection/business_profits_projection/g
%s/payRiseAssumption/pay_rise_assumption/g
%s/SRPMaximum/SRP_Maximum/g
%s/rentAllowanceMaximum/rent_allowance_maximum/g
%s/shareDeduction/share_deduction/g
%s/doHousingCostsLimit/do_housing_costs_limit/g
%s/housing_CostsPersonMax/housing_costs_person_max/g
%s/pensionContributionMax/pension_contribution_max/g
%s/housingAllowances/housing_allowances/g
%s/singlePersonsHousingCostsMax/single_persons_housing_costs_max/g
%s/getSystem/Get_System/g
%s/defaultSystem/Default_System/g
%s/includedIncomes/included_incomes/g
%s/travelExpenses/travel_expenses/g    
%s/unionFees/union_fees/g         
%s/friendlySocs/friendly_societies/g     
%s/loanRepayments/loan_repayments/g     
%s/medicalInsurance/medical_insurance/g   
%s/maintenancePayments/maintenance_payments/g
%s/sharedRent/shared_rent/g         
%s/studentExpenses/student_expenses/g
%s/taxableIncome/taxable_income/g
%s/groundRent/ground_rent/g
%s/serviceCharges/service_charges/g
%s/luncheonVouchers/luncheon_vouchers/g
%s/selfEmployment/self_employment/g
%s/investmentIncome/investment_income/g
%s/pensions/pensions/g
%s/housingAllowances/housing_allowances/g
%s/netRent/net_rent/g
%s/netRates/net_council_tax/g
%s/shareDeduction/share_deduction/g
%s/workRelatedGovtTraining/work_related_govt_training/g
%s/otherIncome/other_income/g
%s/incomeTax/income_tax/g
%s/national_insurance/national_insurance/g
%s/disabilityLivingAllowance/disability_living_allowance/g
%s/attendanceAllowance/attendance_allowance/g
%s/constantAttendanceAllowance/constant_attendance_allowance/g
%s/socialFund/social_fund/g
%s/childBenefit/child_benefit/g
%s/guaranteedPensionCredit/guaranteed_pension_credit/g
%s/savingsPensionCredit/savings_pension_credit/g
%s/retirementPension/retirement_pension/g
%s/widowsPensions/widows_pensions/g
%s/incomeSupport/income_support/g
%s/maternityAllowance/maternity_allowance/g
%s/widowedMothersAllowance/widowed_mothers_allowance/g
%s/warDisablementPension/war_disablement_pension/g
%s/warWidowPension/war_widow_pension/g
%s/severeDisabilityAllowance/severe_disability_allowance/g
%s/disabledPersonsTaxCredit/disabled_persons_tax_credit/g
%s/invalidCareAllowance/invalid_care_allowance/g
%s/incomeRelatedJobseekersAllowance/income_related_jobseekers_allowance/g
%s/contributoryJobseekersAllowance/contributory_jobseekers_allowance/g
%s/industrialInjuryDisablementBenefit/industrial_injury_disablementBenefit/g
%s/incapacityBenefit/incapacity_benefit/g
%s/workingFamiliesTaxCredit/working_families_tax_credit/g
%s/newDeal/new_deal/g
%s/workingTaxCredit/working_tax_credit/g
%s/childTaxCredit/child_tax_credit/g
%s/anyOtherBenefit/any_other_benefit/g
%s/widowsPayment/widows_payment/g
%s/unemploymentRedundancyInsurance/unemployment_redundancy_insurance/g
%s/winterFuelPayments/winter_fuel_payments/g
%s/rentRebates/rent_rebates/g
%s/council_tax_rebates/council_tax_rebates/g
%s/tradeUnion/trade_union/g
%s/friendlySocietyBenefits/friendly_society_benefits/g
%s/privateSicknessScheme/private_sickness_scheme/g
%s/accidentInsuranceScheme/accident_insurance_scheme/g
%s/hospitalSavingsScheme/hospital_savings_scheme/g
%s/healthInsurance/health_insurance/g

:write
:quit 

