--
--  $Author: graham_s $
--  $Date: 2007-11-17 00:08:54 +0000 (Sat, 17 Nov 2007) $
--  $Revision: 4333 $
--
with base_model_types; use base_model_types;
with FRS_Utils;        use FRS_Utils;
--  with data_constants;   use data_constants;

package raw_frs is

   BASE_DATA_DIR      : constant String :=
      "/home/graham_s/VirtualWorlds/projects/scottish_legal_aid/data/";
   MAX_NUM_HOUSEHOLDS : constant := 30000;

   MAX_NUM_PERSONS       : constant := 20;
   MAX_NUM_ADULTS        : constant := 2;
   MAX_NUM_CHILDREN      : constant := 9;
   MAX_NUM_BENEFIT_UNITS : constant := 8;
   MAX_NUM_ENDOWMENTS    : constant := 20;
   MAX_NUM_ACCOUNTS      : constant := 20;
   MAX_NUM_MORTGAGES     : constant := 10;
   MAX_NUM_JOBS          : constant := 10;
   MAX_NUM_pensions      : constant := 20;
   MAX_NUM_MAINTS        : constant := 10;
   MAX_NUM_ASSETS        : constant := 20;
   MAX_NUM_BENEFITS      : constant := 30;
   MAX_NUM_CARES         : constant := 10;
   MAX_NUM_EXT_CHILD     : constant := 10;
   MAX_NUM_GOV_PAY       : constant := 10;
   MAX_NUM_INSURANCES    : constant := 10;
   MAX_NUM_MORT_CONTS    : constant := 10;
   MAX_NUM_VEHICLES      : constant := 10;
   MAX_NUM_ODD_JOBS      : constant := 10;
   MAX_NUM_RENT_CONTS    : constant := 10;

   subtype Care_Count is Integer range 0 .. MAX_NUM_CARES;
   subtype GovPay_Count is Integer range 0 .. MAX_NUM_JOBS;
   subtype Job_Count is Integer range 0 .. MAX_NUM_JOBS;
   subtype Benefit_Count is Integer range 0 .. MAX_NUM_BENEFITS;
   subtype Mortgage_Count is Integer range 0 .. MAX_NUM_MORTGAGES;
   subtype Endowment_Count is Integer range 0 .. MAX_NUM_ENDOWMENTS;
   subtype Maint_Count is Integer range 0 .. MAX_NUM_MAINTS;
   subtype Asset_Count is Integer range 0 .. MAX_NUM_ASSETS;
   subtype Account_Count is Integer range 0 .. MAX_NUM_ACCOUNTS;
   subtype Maintenance_Count is Integer range 0 .. MAX_NUM_MAINTS;
   subtype OddJob_Count is Integer range 0 .. MAX_NUM_ODD_JOBS;
   subtype Pension_Count is Integer range 0 .. MAX_NUM_pensions;
   subtype Child_Count is Integer range 0 .. MAX_NUM_CHILDREN;
   subtype Adult_Count is Integer range 0 .. 2;

   type RecordIndicator is
      record
         startPos : modelint := 0;
         counter  : Integer  := 0;
      end record;

   type Account_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         BENUNIT     : modelint     := MISS;
         PERSON      : modelint     := MISS;
         ACCOUNT     : modelint     := MISS;
         ACCINT      : real         := MISS_R;
         ACCTAX      : modelint     := MISS;
         INVTAX      : modelint     := MISS;
         NSAMT       : modelint     := MISS;
         MONTH       : modelint     := MISS;
      end record;

   type Admin_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         FINDHH      : modelint     := MISS;
         HHSEL       : modelint     := MISS;
         HOUT        : modelint     := MISS;
         NCR1        : modelint     := MISS;
         NCR2        : modelint     := MISS;
         NCR3        : modelint     := MISS;
         NCR4        : modelint     := MISS;
         NCR5        : modelint     := MISS;
         NCR6        : modelint     := MISS;
         NCR7        : modelint     := MISS;
         REFR01      : modelint     := MISS;
         REFR02      : modelint     := MISS;
         REFR03      : modelint     := MISS;
         REFR04      : modelint     := MISS;
         REFR05      : modelint     := MISS;
         REFR06      : modelint     := MISS;
         REFR07      : modelint     := MISS;
         REFR08      : modelint     := MISS;
         REFR09      : modelint     := MISS;
         REFR10      : modelint     := MISS;
         REFR11      : modelint     := MISS;
         REFR12      : modelint     := MISS;
         REFR13      : modelint     := MISS;
         REFR14      : modelint     := MISS;
         REFR15      : modelint     := MISS;
         REFR16      : modelint     := MISS;
         REFR17      : modelint     := MISS;
         REFR18      : modelint     := MISS;
         TNC         : modelint     := MISS;
         VERSION     : modelint     := MISS;
         MONTH       : modelint     := MISS;
      end record;
   type Adult_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         BENUNIT     : modelint     := MISS;
         PERSON      : modelint     := MISS;
         ABS1NO      : modelint     := MISS;
         ABS2NO      : modelint     := MISS;
         ABSPAR      : modelint     := MISS;
         ABSPAY      : modelint     := MISS;
         ABSWHY      : modelint     := MISS;
         ABSWK       : modelint     := MISS;
         X_ACCESS    : modelint     := MISS;
         ACCFTPT     : modelint     := MISS;
         ACCJB       : modelint     := MISS;
         ACCSSAMT    : real         := MISS_R;
         ACCSSPD     : modelint     := MISS;
         ADEDUC      : modelint     := MISS;
         ADEMA       : modelint     := MISS;
         ADEMAAMT    : real         := MISS_R;
         ADEMAPD     : modelint     := MISS;
         AGE         : modelint     := MISS;
         ALLOW1      : modelint     := MISS;
         ALLOW2      : modelint     := MISS;
         ALLOW3      : modelint     := MISS;
         ALLOW4      : modelint     := MISS;
         ALLPAY1     : real         := MISS_R;
         ALLPAY2     : real         := MISS_R;
         ALLPAY3     : real         := MISS_R;
         ALLPAY4     : real         := MISS_R;
         ALLPD1      : modelint     := MISS;
         ALLPD2      : modelint     := MISS;
         ALLPD3      : modelint     := MISS;
         ALLPD4      : modelint     := MISS;
         ANYACC      : modelint     := MISS;
         ANYED       : modelint     := MISS;
         ANYMON      : modelint     := MISS;
         ANYPEN1     : modelint     := MISS;
         ANYPEN2     : modelint     := MISS;
         ANYPEN3     : modelint     := MISS;
         ANYPEN4     : modelint     := MISS;
         ANYPEN5     : modelint     := MISS;
         ANYPEN6     : modelint     := MISS;
         ANYPEN7     : modelint     := MISS;
         APAMT       : real         := MISS_R;
         APDAMT      : real         := MISS_R;
         APDIR       : modelint     := MISS;
         APDPD       : modelint     := MISS;
         APPD        : modelint     := MISS;
         B2QFUT1     : modelint     := MISS;
         B2QFUT2     : modelint     := MISS;
         B2QFUT3     : modelint     := MISS;
         B3QFUT1     : modelint     := MISS;
         B3QFUT2     : modelint     := MISS;
         B3QFUT3     : modelint     := MISS;
         B3QFUT4     : modelint     := MISS;
         B3QFUT5     : modelint     := MISS;
         B3QFUT6     : modelint     := MISS;
         BEN1Q1      : modelint     := MISS;
         BEN1Q2      : modelint     := MISS;
         BEN1Q3      : modelint     := MISS;
         BEN1Q4      : modelint     := MISS;
         BEN1Q5      : modelint     := MISS;
         BEN1Q6      : modelint     := MISS;
         BEN1Q7      : modelint     := MISS;
         BEN2Q1      : modelint     := MISS;
         BEN2Q2      : modelint     := MISS;
         BEN2Q3      : modelint     := MISS;
         BEN3Q1      : modelint     := MISS;
         BEN3Q2      : modelint     := MISS;
         BEN3Q3      : modelint     := MISS;
         BEN3Q4      : modelint     := MISS;
         BEN3Q5      : modelint     := MISS;
         BEN3Q6      : modelint     := MISS;
         BEN4Q1      : modelint     := MISS;
         BEN4Q2      : modelint     := MISS;
         BEN4Q3      : modelint     := MISS;
         BEN5Q1      : modelint     := MISS;
         BEN5Q2      : modelint     := MISS;
         BEN5Q3      : modelint     := MISS;
         BEN5Q4      : modelint     := MISS;
         BEN5Q5      : modelint     := MISS;
         BEN5Q6      : modelint     := MISS;
         BEN7Q1      : modelint     := MISS;
         BEN7Q2      : modelint     := MISS;
         BEN7Q3      : modelint     := MISS;
         BEN7Q4      : modelint     := MISS;
         BEN7Q5      : modelint     := MISS;
         BEN7Q6      : modelint     := MISS;
         BEN7Q7      : modelint     := MISS;
         BEN7Q8      : modelint     := MISS;
         BEN7Q9      : modelint     := MISS;
         BTWACC      : modelint     := MISS;
         CLAIMANT    : modelint     := MISS;
         COHABIT     : modelint     := MISS;
         COMBID      : modelint     := MISS;
         CONVBL      : modelint     := MISS;
         CTCLUM1     : modelint     := MISS;
         CTCLUM2     : modelint     := MISS;
         CUPCHK      : modelint     := MISS;
         CVHT        : modelint     := MISS;
         CVPAY       : real         := MISS_R;
         CVPD        : modelint     := MISS;
         DENTIST     : modelint     := MISS;
         DEPEND      : modelint     := MISS;
         DISDIF1     : modelint     := MISS;
         DISDIF2     : modelint     := MISS;
         DISDIF3     : modelint     := MISS;
         DISDIF4     : modelint     := MISS;
         DISDIF5     : modelint     := MISS;
         DISDIF6     : modelint     := MISS;
         DISDIF7     : modelint     := MISS;
         DISDIF8     : modelint     := MISS;
         DOB         : modelint     := MISS;
         DPTCBOTH    : modelint     := MISS;
         DPTCLUM     : modelint     := MISS;
         DVIL03A     : modelint     := MISS;
         DVIL04A     : modelint     := MISS;
         DVJB12ML    : modelint     := MISS;
         DVMARDF     : modelint     := MISS;
         ED1AMT      : real         := MISS_R;
         ED1BORR     : modelint     := MISS;
         ED1INT      : modelint     := MISS;
         ED1MONYR    : modelint     := MISS;
         ED1PD       : modelint     := MISS;
         ED1SUM      : modelint     := MISS;
         ED2AMT      : real         := MISS_R;
         ED2BORR     : modelint     := MISS;
         ED2INT      : modelint     := MISS;
         ED2MONYR    : modelint     := MISS;
         ED2PD       : modelint     := MISS;
         ED2SUM      : modelint     := MISS;
         EDATT       : modelint     := MISS;
         EDATTN1     : modelint     := MISS;
         EDATTN2     : modelint     := MISS;
         EDATTN3     : modelint     := MISS;
         EDHR        : modelint     := MISS;
         EDTIME      : modelint     := MISS;
         EDTYP       : modelint     := MISS;
         ELIGADLT    : modelint     := MISS;
         ELIGCHLD    : modelint     := MISS;
         EMPPAY1     : modelint     := MISS;
         EMPPAY2     : modelint     := MISS;
         EMPPAY3     : modelint     := MISS;
         EMPSTAT     : modelint     := MISS;
         ENDYR       : modelint     := MISS;
         EPCUR       : modelint     := MISS;
         ES2000      : modelint     := MISS;
         ETHGRP      : modelint     := MISS;
         EVERWRK     : modelint     := MISS;
         EXTHBCT1    : modelint     := MISS;
         EXTHBCT2    : modelint     := MISS;
         EXTHBCT3    : modelint     := MISS;
         EYETEST     : modelint     := MISS;
         FOLLOW      : modelint     := MISS;
         FTED        : modelint     := MISS;
         FTWK        : modelint     := MISS;
         FUTURE      : modelint     := MISS;
         GOVPIS      : modelint     := MISS;
         GOVPJSA     : modelint     := MISS;
         GRANT       : modelint     := MISS;
         GRTAMT1     : real         := MISS_R;
         GRTAMT2     : real         := MISS_R;
         GRTDIR1     : real         := MISS_R;
         GRTDIR2     : real         := MISS_R;
         GRTNUM      : modelint     := MISS;
         GRTSCE1     : modelint     := MISS;
         GRTSCE2     : modelint     := MISS;
         GRTVAL1     : real         := MISS_R;
         GRTVAL2     : real         := MISS_R;
         GTA         : modelint     := MISS;
         HBOTHAMT    : real         := MISS_R;
         HBOTHBU     : modelint     := MISS;
         HBOTHPD     : modelint     := MISS;
         HBOTHWK     : modelint     := MISS;
         HBOTWAIT    : modelint     := MISS;
         HEALTH      : modelint     := MISS;
         HHOLDER     : modelint     := MISS;
         HOSP        : modelint     := MISS;
         HPROB       : modelint     := MISS;
         HRPID       : modelint     := MISS;
         INCDUR      : modelint     := MISS;
         INJLONG     : modelint     := MISS;
         INJWK       : modelint     := MISS;
         INVESTS     : modelint     := MISS;
         IOUT        : modelint     := MISS;
         ISA1TYPE    : modelint     := MISS;
         ISA2TYPE    : modelint     := MISS;
         ISA3TYPE    : modelint     := MISS;
         JOBAWAY     : modelint     := MISS;
         LAREG       : modelint     := MISS;
         LIKEWK      : modelint     := MISS;
         LKTIME      : modelint     := MISS;
         LN1RPINT    : modelint     := MISS;
         LN2RPINT    : modelint     := MISS;
         LOAN        : modelint     := MISS;
         LOANNUM     : modelint     := MISS;
         LOOK        : modelint     := MISS;
         LOOKWK      : modelint     := MISS;
         LSTWRK1     : modelint     := MISS;
         LSTWRK2     : modelint     := MISS;
         LSTYR       : modelint     := MISS;
         MNTAMT1     : real         := MISS_R;
         MNTAMT2     : real         := MISS_R;
         MNTCT       : modelint     := MISS;
         MNTFOR1     : modelint     := MISS;
         MNTFOR2     : modelint     := MISS;
         MNTGOV1     : modelint     := MISS;
         MNTGOV2     : modelint     := MISS;
         MNTPAY      : modelint     := MISS;
         MNTPD1      : modelint     := MISS;
         MNTPD2      : modelint     := MISS;
         MNTREC      : modelint     := MISS;
         MNTTOTA1    : modelint     := MISS;
         MNTTOTA2    : modelint     := MISS;
         MNTUS1      : modelint     := MISS;
         MNTUS2      : modelint     := MISS;
         MNTUSAM1    : real         := MISS_R;
         MNTUSAM2    : real         := MISS_R;
         MNTUSPD1    : modelint     := MISS;
         MNTUSPD2    : modelint     := MISS;
         MS          : modelint     := MISS;
         NATID1      : modelint     := MISS;
         NATID2      : modelint     := MISS;
         NATID3      : modelint     := MISS;
         NATID4      : modelint     := MISS;
         NATID5      : modelint     := MISS;
         NATID6      : modelint     := MISS;
         NDEAL       : modelint     := MISS;
         NEWDTYPE    : modelint     := MISS;
         NHS1        : modelint     := MISS;
         NHS2        : modelint     := MISS;
         NHS3        : modelint     := MISS;
         NIAMT       : real         := MISS_R;
         NIETHGRP    : modelint     := MISS;
         NIEXTHBB    : modelint     := MISS;
         NINATID1    : modelint     := MISS;
         NINATID2    : modelint     := MISS;
         NINATID3    : modelint     := MISS;
         NINATID4    : modelint     := MISS;
         NINATID5    : modelint     := MISS;
         NINATID6    : modelint     := MISS;
         NINATID7    : modelint     := MISS;
         NINATID8    : modelint     := MISS;
         NIPD        : modelint     := MISS;
         NIREG       : modelint     := MISS;
         NIREL       : modelint     := MISS;
         NITRAIN     : modelint     := MISS;
         NLPER       : modelint     := MISS;
         NOLK1       : modelint     := MISS;
         NOLK2       : modelint     := MISS;
         NOLK3       : modelint     := MISS;
         NOLOOK      : modelint     := MISS;
         NOWANT      : modelint     := MISS;
         NSSEC       : real         := MISS_R;
         NTCAPP      : modelint     := MISS;
         NTCDAT      : modelint     := MISS;
         NTCINC      : real         := MISS_R;
         NTCORIG1    : modelint     := MISS;
         NTCORIG2    : modelint     := MISS;
         NTCORIG3    : modelint     := MISS;
         NTCORIG4    : modelint     := MISS;
         NTCORIG5    : modelint     := MISS;
         NUMJOB      : modelint     := MISS;
         NUMJOB2     : modelint     := MISS;
         ODDJOB      : modelint     := MISS;
         OLDSTUD     : modelint     := MISS;
         OTABSPAR    : modelint     := MISS;
         OTAMT       : real         := MISS_R;
         OTAPAMT     : real         := MISS_R;
         OTAPPD      : modelint     := MISS;
         OTHTAX      : modelint     := MISS;
         OTINVA      : modelint     := MISS;
         PAREAMT     : real         := MISS_R;
         PAREPD      : modelint     := MISS;
         PENLUMP     : modelint     := MISS;
         PPNUMC      : modelint     := MISS;
         PRIT        : modelint     := MISS;
         PRSCRPT     : modelint     := MISS;
         PTWK        : modelint     := MISS;
         R01         : modelint     := MISS;
         R02         : modelint     := MISS;
         R03         : modelint     := MISS;
         R04         : modelint     := MISS;
         R05         : modelint     := MISS;
         R06         : modelint     := MISS;
         R07         : modelint     := MISS;
         R08         : modelint     := MISS;
         R09         : modelint     := MISS;
         R10         : modelint     := MISS;
         R11         : modelint     := MISS;
         R12         : modelint     := MISS;
         R13         : modelint     := MISS;
         R14         : modelint     := MISS;
         REDAMT      : real         := MISS_R;
         REDANY      : modelint     := MISS;
         RENTPROF    : modelint     := MISS;
         RETIRE      : modelint     := MISS;
         RETIRE1     : modelint     := MISS;
         RETREAS     : modelint     := MISS;
         ROYAL1      : modelint     := MISS;
         ROYAL2      : modelint     := MISS;
         ROYAL3      : modelint     := MISS;
         ROYAL4      : modelint     := MISS;
         ROYYR1      : real         := MISS_R;
         ROYYR2      : real         := MISS_R;
         ROYYR3      : real         := MISS_R;
         ROYYR4      : real         := MISS_R;
         RSTRCT      : modelint     := MISS;
         SEX         : modelint     := MISS;
         SFLNTYP1    : modelint     := MISS;
         SFLNTYP2    : modelint     := MISS;
         SFTYPE1     : modelint     := MISS;
         SFTYPE2     : modelint     := MISS;
         SIC         : modelint     := MISS;
         SLREPAMT    : real         := MISS_R;
         SLREPAY     : modelint     := MISS;
         SLREPPD     : modelint     := MISS;
         SOC2000     : modelint     := MISS;
         SPCREG1     : modelint     := MISS;
         SPCREG2     : modelint     := MISS;
         SPCREG3     : modelint     := MISS;
         SPECS       : modelint     := MISS;
         SPOUT       : modelint     := MISS;
         SRENTAMT    : real         := MISS_R;
         SRENTPD     : modelint     := MISS;
         START       : modelint     := MISS;
         STARTYR     : modelint     := MISS;
         TAXCRED1    : modelint     := MISS;
         TAXCRED2    : modelint     := MISS;
         TAXCRED3    : modelint     := MISS;
         TAXCRED4    : modelint     := MISS;
         TAXCRED5    : modelint     := MISS;
         TAXFUT      : modelint     := MISS;
         TDAYWRK     : modelint     := MISS;
         TEA         : modelint     := MISS;
         TOPUPL      : modelint     := MISS;
         TOTINT      : real         := MISS_R;
         TRAIN       : modelint     := MISS;
         TRAV        : modelint     := MISS;
         TUBORR      : modelint     := MISS;
         TYPEED      : modelint     := MISS;
         UNPAID1     : modelint     := MISS;
         UNPAID2     : modelint     := MISS;
         VOUCHER     : modelint     := MISS;
         W1          : modelint     := MISS;
         W2          : modelint     := MISS;
         WAIT        : modelint     := MISS;
         WAR1        : modelint     := MISS;
         WAR2        : modelint     := MISS;
         WFTCBOTH    : modelint     := MISS;
         WFTCLUM     : modelint     := MISS;
         WHORESP     : modelint     := MISS;
         WHOSECTB    : modelint     := MISS;
         WHYFRDE1    : modelint     := MISS;
         WHYFRDE2    : modelint     := MISS;
         WHYFRDE3    : modelint     := MISS;
         WHYFRDE4    : modelint     := MISS;
         WHYFRDE5    : modelint     := MISS;
         WHYFRDE6    : modelint     := MISS;
         WHYFREY1    : modelint     := MISS;
         WHYFREY2    : modelint     := MISS;
         WHYFREY3    : modelint     := MISS;
         WHYFREY4    : modelint     := MISS;
         WHYFREY5    : modelint     := MISS;
         WHYFREY6    : modelint     := MISS;
         WHYFRPR1    : modelint     := MISS;
         WHYFRPR2    : modelint     := MISS;
         WHYFRPR3    : modelint     := MISS;
         WHYFRPR4    : modelint     := MISS;
         WHYFRPR5    : modelint     := MISS;
         WHYFRPR6    : modelint     := MISS;
         WHYTRAV1    : modelint     := MISS;
         WHYTRAV2    : modelint     := MISS;
         WHYTRAV3    : modelint     := MISS;
         WHYTRAV4    : modelint     := MISS;
         WHYTRAV5    : modelint     := MISS;
         WHYTRAV6    : modelint     := MISS;
         WINTFUEL    : modelint     := MISS;
         WMKIT       : modelint     := MISS;
         WORKING     : modelint     := MISS;
         WPA         : modelint     := MISS;
         WPBA        : modelint     := MISS;
         WTCLUM1     : modelint     := MISS;
         WTCLUM2     : modelint     := MISS;
         WTCLUM3     : modelint     := MISS;
         YSTRTWK     : modelint     := MISS;
         MONTH       : modelint     := MISS;
         ABLE        : modelint     := MISS;
         ACTACCI     : modelint     := MISS;
         ADDDA       : modelint     := MISS;
         BASACTI     : modelint     := MISS;
         BNTXCRED    : real         := MISS_R;
         CAREAB      : modelint     := MISS;
         CAREAH      : modelint     := MISS;
         CARECB      : modelint     := MISS;
         CARECH      : modelint     := MISS;
         CARECL      : modelint     := MISS;
         CAREFL      : modelint     := MISS;
         CAREFR      : modelint     := MISS;
         CAREOT      : modelint     := MISS;
         CARERE      : modelint     := MISS;
         CURACTI     : modelint     := MISS;
         EMPOCCP     : real         := MISS_R;
         EMPSTATB    : modelint     := MISS;
         EMPSTATC    : modelint     := MISS;
         EMPSTATI    : modelint     := MISS;
         FSBNDCTI    : modelint     := MISS;
         FWMLKVAL    : real         := MISS_R;
         GEBACTI     : modelint     := MISS;
         GILTCTI     : modelint     := MISS;
         GROSS2      : modelint     := MISS;
         GROSS3      : modelint     := MISS;
         HBSUPRAN    : real         := MISS_R;
         HDAGE       : modelint     := MISS;
         HDBEN       : modelint     := MISS;
         HDINDINC    : modelint     := MISS;
         HOURAB      : modelint     := MISS;
         HOURAH      : modelint     := MISS;
         HOURCARE    : real         := MISS_R;
         HOURCB      : modelint     := MISS;
         HOURCH      : modelint     := MISS;
         HOURCL      : modelint     := MISS;
         HOURFR      : modelint     := MISS;
         HOUROT      : modelint     := MISS;
         HOURRE      : modelint     := MISS;
         HOURTOT     : modelint     := MISS;
         HPERSON     : modelint     := MISS;
         IAGEGR2     : modelint     := MISS;
         IAGEGRP     : modelint     := MISS;
         INCSEO2     : real         := MISS_R;
         INDINC      : real         := MISS_R;
         INDISBEN    : real         := MISS_R;
         INEARNS     : real         := MISS_R;
         ININV       : real         := MISS_R;
         INIRBEN     : real         := MISS_R;
         INNIRBEN    : real         := MISS_R;
         INOTHBEN    : real         := MISS_R;
         INPENINC    : real         := MISS_R;
         INRINC      : real         := MISS_R;
         INRPINC     : real         := MISS_R;
         INTVLIC     : real         := MISS_R;
         INTXCRED    : real         := MISS_R;
         ISACTI      : modelint     := MISS;
         MARITAL     : modelint     := MISS;
         NETOCPEN    : real         := MISS_R;
         NINCSEO2    : real         := MISS_R;
         NINDINC     : real         := MISS_R;
         NINEARNS    : real         := MISS_R;
         NININV      : real         := MISS_R;
         NINPENIN    : real         := MISS_R;
         NINSEIN2    : real         := MISS_R;
         NSBOCTI     : modelint     := MISS;
         OCCUPNUM    : modelint     := MISS;
         OTBSCTI     : modelint     := MISS;
         PEPSCTI     : modelint     := MISS;
         POACCTI     : modelint     := MISS;
         PRBOCTI     : modelint     := MISS;
         RELHRP      : modelint     := MISS;
         SAYECTI     : modelint     := MISS;
         SCLBCTI     : modelint     := MISS;
         SEINCAM2    : real         := MISS_R;
         SMPADJ      : real         := MISS_R;
         SSCTI       : modelint     := MISS;
         SSPADJ      : real         := MISS_R;
         STSHCTI     : modelint     := MISS;
         SUPERAN     : real         := MISS_R;
         TAXPAYER    : modelint     := MISS;
         TESSCTI     : modelint     := MISS;
         TOTGRANT    : real         := MISS_R;
         TOTHOURS    : real         := MISS_R;
         TOTOCCP     : real         := MISS_R;
         TTWCOSTS    : real         := MISS_R;
         UNTRCTI     : modelint     := MISS;
         UPERSON     : modelint     := MISS;
         WIDOCCP     : real         := MISS_R;
         ACCOUNTQ    : modelint     := MISS;
         BEN5Q7      : modelint     := MISS;
         BEN5Q8      : modelint     := MISS;
         BEN5Q9      : modelint     := MISS;
         DDATRE      : modelint     := MISS;
         DISDIF9     : modelint     := MISS;
         FARE        : real         := MISS_R;
         NITTWMOD    : modelint     := MISS;
         ONEWAY      : modelint     := MISS;
         PSSAMT      : real         := MISS_R;
         PSSDATE     : modelint     := MISS;
         TTWCODE1    : modelint     := MISS;
         TTWCODE2    : modelint     := MISS;
         TTWCODE3    : modelint     := MISS;
         TTWCOST     : real         := MISS_R;
         TTWFAR      : modelint     := MISS;
         TTWFRQ      : real         := MISS_R;
         TTWMOD      : modelint     := MISS;
         TTWPAY      : modelint     := MISS;
         TTWPSS      : modelint     := MISS;
         TTWREC      : real         := MISS_R;
         CHBFLG      : modelint     := MISS;
         CRUNACI     : modelint     := MISS;
         ENOMORTI    : modelint     := MISS;
         SAPADJ      : modelint     := MISS;
         SPPADJ      : real         := MISS_R;
         TTWMODE     : modelint     := MISS;
      end record;

   type Asset_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         BENUNIT     : modelint     := MISS;
         PERSON      : modelint     := MISS;
         ASSETYPE    : modelint     := MISS;
         SEQ         : modelint     := MISS;
         ACCNAME     : modelint     := MISS;
         AMOUNT      : real         := MISS_R;
         ANYMON      : modelint     := MISS;
         HOWMANY     : modelint     := MISS;
         HOWMUCH     : real         := MISS_R;
         HOWMUCHE    : modelint     := MISS;
         INTRO       : modelint     := MISS;
         ISSDATE     : modelint     := MISS;
         ISSVAL      : real         := MISS_R;
         PD          : modelint     := MISS;
         MONTH       : modelint     := MISS;
      end record;

   type Benefit_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         BENUNIT     : modelint     := MISS;
         PERSON      : modelint     := MISS;
         BENEFIT     : modelint     := MISS;
         BANKSTMT    : modelint     := MISS;
         BENAMT      : real         := MISS_R;
         BENAMTDK    : modelint     := MISS;
         BENLETTR    : modelint     := MISS;
         BENPD       : modelint     := MISS;
         BOOKCARD    : modelint     := MISS;
         CCTC        : modelint     := MISS;
         COMBAMT     : real         := MISS_R;
         COMBBK      : modelint     := MISS;
         COMBPD      : modelint     := MISS;
         HOWBEN      : modelint     := MISS;
         NOTUSAMT    : real         := MISS_R;
         NOTUSPD     : modelint     := MISS;
         NUMWEEKS    : modelint     := MISS;
         ORDBKNO     : modelint     := MISS;
         PAYSLIPB    : modelint     := MISS;
         PRES        : modelint     := MISS;
         USUAL       : modelint     := MISS;
         VAR1        : modelint     := MISS;
         VAR2        : modelint     := MISS;
         VAR3        : modelint     := MISS;
         WHOREC1     : modelint     := MISS;
         WHOREC2     : modelint     := MISS;
         WHOREC3     : modelint     := MISS;
         WHOREC4     : modelint     := MISS;
         WHOREC5     : modelint     := MISS;
         MONTH       : modelint     := MISS;
      end record;

   type Benunit_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         BENUNIT     : modelint     := MISS;
         INCCHNGE    : modelint     := MISS;
         INCHILOW    : modelint     := MISS;
         KIDINC      : modelint     := MISS;
         NHHCHILD    : modelint     := MISS;
         TOTSAV      : modelint     := MISS;
         MONTH       : modelint     := MISS;
         ACTACCB     : modelint     := MISS;
         ADDDABU     : modelint     := MISS;
         ADULTB      : modelint     := MISS;
         BASACTB     : modelint     := MISS;
         BOARDER     : real         := MISS_R;
         BPENINC     : real         := MISS_R;
         BSEINC      : real         := MISS_R;
         BUAGEGR2    : modelint     := MISS;
         BUAGEGRP    : modelint     := MISS;
         BUDISBEN    : real         := MISS_R;
         BUEARNS     : real         := MISS_R;
         BUETHGR2    : modelint     := MISS;
         BUETHGRP    : modelint     := MISS;
         BUINC       : real         := MISS_R;
         BUINV       : real         := MISS_R;
         BUIRBEN     : real         := MISS_R;
         BUKIDS      : modelint     := MISS;
         BUNIRBEN    : real         := MISS_R;
         BUOTHBEN    : real         := MISS_R;
         BURENT      : real         := MISS_R;
         BURINC      : real         := MISS_R;
         BURPINC     : real         := MISS_R;
         BUTVLIC     : real         := MISS_R;
         BUTXCRED    : real         := MISS_R;
         CHDDABU     : modelint     := MISS;
         CURACTB     : modelint     := MISS;
         DEPCHLDB    : modelint     := MISS;
         DEPDEDS     : modelint     := MISS;
         DISINDHB    : modelint     := MISS;
         ECOTYPBU    : modelint     := MISS;
         ECSTATBU    : modelint     := MISS;
         FAMTHBAI    : modelint     := MISS;
         FAMTYPBS    : modelint     := MISS;
         FAMTYPBU    : modelint     := MISS;
         FAMTYPE     : modelint     := MISS;
         FSBNDCTB    : modelint     := MISS;
         FSMBU       : real         := MISS_R;
         FSMLKBU     : real         := MISS_R;
         FWMLKBU     : real         := MISS_R;
         GEBACTB     : modelint     := MISS;
         GILTCTB     : modelint     := MISS;
         GROSS2      : modelint     := MISS;
         GROSS3      : modelint     := MISS;
         HBINDBU     : modelint     := MISS;
         ISACTB      : modelint     := MISS;
         KID04       : modelint     := MISS;
         KID1115     : modelint     := MISS;
         KID1618     : modelint     := MISS;
         KID510      : modelint     := MISS;
         KIDSBU0     : modelint     := MISS;
         KIDSBU1     : modelint     := MISS;
         KIDSBU10    : modelint     := MISS;
         KIDSBU11    : modelint     := MISS;
         KIDSBU12    : modelint     := MISS;
         KIDSBU13    : modelint     := MISS;
         KIDSBU14    : modelint     := MISS;
         KIDSBU15    : modelint     := MISS;
         KIDSBU16    : modelint     := MISS;
         KIDSBU17    : modelint     := MISS;
         KIDSBU18    : modelint     := MISS;
         KIDSBU2     : modelint     := MISS;
         KIDSBU3     : modelint     := MISS;
         KIDSBU4     : modelint     := MISS;
         KIDSBU5     : modelint     := MISS;
         KIDSBU6     : modelint     := MISS;
         KIDSBU7     : modelint     := MISS;
         KIDSBU8     : modelint     := MISS;
         KIDSBU9     : modelint     := MISS;
         LASTWORK    : modelint     := MISS;
         LODGER      : real         := MISS_R;
         NSBOCTB     : modelint     := MISS;
         OTBSCTB     : modelint     := MISS;
         PEPSCTB     : modelint     := MISS;
         POACCTB     : modelint     := MISS;
         PRBOCTB     : modelint     := MISS;
         SAYECTB     : modelint     := MISS;
         SCLBCTB     : modelint     := MISS;
         SSCTB       : modelint     := MISS;
         STSHCTB     : modelint     := MISS;
         SUBLTAMT    : real         := MISS_R;
         TESSCTB     : modelint     := MISS;
         TOTCAPBU    : real         := MISS_R;
         TOTSAVBU    : modelint     := MISS;
         TUBURENT    : real         := MISS_R;
         UNTRCTB     : modelint     := MISS;
         YOUNGCH     : modelint     := MISS;
         ADDDEC      : modelint     := MISS;
         ADDEPLES    : modelint     := MISS;
         ADDHOL      : modelint     := MISS;
         ADDINS      : modelint     := MISS;
         ADDMEL      : modelint     := MISS;
         ADDMON      : modelint     := MISS;
         ADDSHOE     : modelint     := MISS;
         ADEPFUR     : modelint     := MISS;
         AF1         : modelint     := MISS;
         AFDEP2      : modelint     := MISS;
         CDELPLY     : modelint     := MISS;
         CDEPBED     : modelint     := MISS;
         CDEPCEL     : modelint     := MISS;
         CDEPEQP     : modelint     := MISS;
         CDEPHOL     : modelint     := MISS;
         CDEPLES     : modelint     := MISS;
         CDEPSUM     : modelint     := MISS;
         CDEPTEA     : modelint     := MISS;
         CDEPTRP     : modelint     := MISS;
         CPLAY       : modelint     := MISS;
         DEBT1       : modelint     := MISS;
         DEBT2       : modelint     := MISS;
         DEBT3       : modelint     := MISS;
         DEBT4       : modelint     := MISS;
         DEBT5       : modelint     := MISS;
         DEBT6       : modelint     := MISS;
         DEBT7       : modelint     := MISS;
         DEBT8       : modelint     := MISS;
         DEBT9       : modelint     := MISS;
         HOUSHE1     : modelint     := MISS;
         INCOLD      : modelint     := MISS;
         CRUNACB     : modelint     := MISS;
         ENOMORTB    : modelint     := MISS;
      end record;

   type Care_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         BENUNIT     : modelint     := MISS;
         NEEDPER     : modelint     := MISS;
         DAYNIGHT    : modelint     := MISS;
         FREQ        : modelint     := MISS;
         HOUR01      : modelint     := MISS;
         HOUR02      : modelint     := MISS;
         HOUR03      : modelint     := MISS;
         HOUR04      : modelint     := MISS;
         HOUR05      : modelint     := MISS;
         HOUR06      : modelint     := MISS;
         HOUR07      : modelint     := MISS;
         HOUR08      : modelint     := MISS;
         HOUR09      : modelint     := MISS;
         HOUR10      : modelint     := MISS;
         HOUR11      : modelint     := MISS;
         HOUR12      : modelint     := MISS;
         HOUR13      : modelint     := MISS;
         HOUR14      : modelint     := MISS;
         HOUR15      : modelint     := MISS;
         HOUR16      : modelint     := MISS;
         HOUR17      : modelint     := MISS;
         HOUR18      : modelint     := MISS;
         HOUR19      : modelint     := MISS;
         HOUR20      : modelint     := MISS;
         WHOLOO01    : modelint     := MISS;
         WHOLOO02    : modelint     := MISS;
         WHOLOO03    : modelint     := MISS;
         WHOLOO04    : modelint     := MISS;
         WHOLOO05    : modelint     := MISS;
         WHOLOO06    : modelint     := MISS;
         WHOLOO07    : modelint     := MISS;
         WHOLOO08    : modelint     := MISS;
         WHOLOO09    : modelint     := MISS;
         WHOLOO10    : modelint     := MISS;
         WHOLOO11    : modelint     := MISS;
         WHOLOO12    : modelint     := MISS;
         WHOLOO13    : modelint     := MISS;
         WHOLOO14    : modelint     := MISS;
         WHOLOO15    : modelint     := MISS;
         WHOLOO16    : modelint     := MISS;
         WHOLOO17    : modelint     := MISS;
         WHOLOO18    : modelint     := MISS;
         WHOLOO19    : modelint     := MISS;
         WHOLOO20    : modelint     := MISS;
         MONTH       : modelint     := MISS;
      end record;

   type Child_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         BENUNIT     : modelint     := MISS;
         PERSON      : modelint     := MISS;
         ADEDUC      : modelint     := MISS;
         AGE         : modelint     := MISS;
         BENCCDIS    : modelint     := MISS;
         CARE        : modelint     := MISS;
         CDISDIF1    : modelint     := MISS;
         CDISDIF2    : modelint     := MISS;
         CDISDIF3    : modelint     := MISS;
         CDISDIF4    : modelint     := MISS;
         CDISDIF5    : modelint     := MISS;
         CDISDIF6    : modelint     := MISS;
         CDISDIF7    : modelint     := MISS;
         CDISDIF8    : modelint     := MISS;
         CHAMT1      : real         := MISS_R;
         CHAMT2      : real         := MISS_R;
         CHAMT3      : real         := MISS_R;
         CHAMT4      : real         := MISS_R;
         CHAMTERN    : real         := MISS_R;
         CHAMTTST    : real         := MISS_R;
         CHDLA1      : modelint     := MISS;
         CHDLA2      : modelint     := MISS;
         CHEALTH     : modelint     := MISS;
         CHEARNS1    : modelint     := MISS;
         CHEARNS2    : modelint     := MISS;
         CHEMA       : modelint     := MISS;
         CHEMAAMT    : real         := MISS_R;
         CHEMAPD     : modelint     := MISS;
         CHFAR       : modelint     := MISS;
         CHHR1       : modelint     := MISS;
         CHHR2       : modelint     := MISS;
         CHLOOK01    : modelint     := MISS;
         CHLOOK02    : modelint     := MISS;
         CHLOOK03    : modelint     := MISS;
         CHLOOK04    : modelint     := MISS;
         CHLOOK05    : modelint     := MISS;
         CHLOOK06    : modelint     := MISS;
         CHLOOK07    : modelint     := MISS;
         CHLOOK08    : modelint     := MISS;
         CHLOOK09    : modelint     := MISS;
         CHLOOK10    : modelint     := MISS;
         CHPAY1      : modelint     := MISS;
         CHPAY2      : modelint     := MISS;
         CHPAY3      : modelint     := MISS;
         CHPDERN     : modelint     := MISS;
         CHPDTST     : modelint     := MISS;
         CHPROB      : modelint     := MISS;
         CHSAVE      : modelint     := MISS;
         CHWKERN     : modelint     := MISS;
         CHWKTST     : modelint     := MISS;
         CHYRERN     : modelint     := MISS;
         CHYRTST     : modelint     := MISS;
         CLONE       : modelint     := MISS;
         COHABIT     : modelint     := MISS;
         CONVBL      : modelint     := MISS;
         COST        : modelint     := MISS;
         CVHT        : modelint     := MISS;
         CVPAY       : real         := MISS_R;
         CVPD        : modelint     := MISS;
         DENTIST     : modelint     := MISS;
         DEPEND      : modelint     := MISS;
         DOB         : modelint     := MISS;
         ELIGADLT    : modelint     := MISS;
         ELIGCHLD    : modelint     := MISS;
         ENDYR       : modelint     := MISS;
         EYETEST     : modelint     := MISS;
         FTED        : modelint     := MISS;
         GRANT       : modelint     := MISS;
         GRTAMT1     : real         := MISS_R;
         GRTAMT2     : real         := MISS_R;
         GRTDIR1     : real         := MISS_R;
         GRTDIR2     : real         := MISS_R;
         GRTNUM      : modelint     := MISS;
         GRTSCE1     : modelint     := MISS;
         GRTSCE2     : modelint     := MISS;
         GRTVAL1     : real         := MISS_R;
         GRTVAL2     : real         := MISS_R;
         HHOLDER     : modelint     := MISS;
         HOSP        : modelint     := MISS;
         LAREG       : modelint     := MISS;
         LEGDEP      : modelint     := MISS;
         MS          : modelint     := MISS;
         NHS1        : modelint     := MISS;
         NHS2        : modelint     := MISS;
         NHS3        : modelint     := MISS;
         PARENT1     : modelint     := MISS;
         PARENT2     : modelint     := MISS;
         PRIT        : modelint     := MISS;
         PRSCRPT     : modelint     := MISS;
         R01         : modelint     := MISS;
         R02         : modelint     := MISS;
         R03         : modelint     := MISS;
         R04         : modelint     := MISS;
         R05         : modelint     := MISS;
         R06         : modelint     := MISS;
         R07         : modelint     := MISS;
         R08         : modelint     := MISS;
         R09         : modelint     := MISS;
         R10         : modelint     := MISS;
         R11         : modelint     := MISS;
         R12         : modelint     := MISS;
         R13         : modelint     := MISS;
         R14         : modelint     := MISS;
         REGISTR1    : modelint     := MISS;
         REGISTR2    : modelint     := MISS;
         REGISTR3    : modelint     := MISS;
         REGISTR4    : modelint     := MISS;
         REGISTR5    : modelint     := MISS;
         SEX         : modelint     := MISS;
         SMKIT       : modelint     := MISS;
         SMLIT       : modelint     := MISS;
         SPCREG1     : modelint     := MISS;
         SPCREG2     : modelint     := MISS;
         SPCREG3     : modelint     := MISS;
         SPECS       : modelint     := MISS;
         SPOUT       : modelint     := MISS;
         SRENTAMT    : real         := MISS_R;
         SRENTPD     : modelint     := MISS;
         STARTYR     : modelint     := MISS;
         TOTSAVE     : modelint     := MISS;
         TRAV        : modelint     := MISS;
         TYPEED      : modelint     := MISS;
         VOUCHER     : modelint     := MISS;
         WHYTRAV1    : modelint     := MISS;
         WHYTRAV2    : modelint     := MISS;
         WHYTRAV3    : modelint     := MISS;
         WHYTRAV4    : modelint     := MISS;
         WHYTRAV5    : modelint     := MISS;
         WHYTRAV6    : modelint     := MISS;
         WMKIT       : modelint     := MISS;
         MONTH       : modelint     := MISS;
         CAREAB      : modelint     := MISS;
         CAREAH      : modelint     := MISS;
         CARECB      : modelint     := MISS;
         CARECH      : modelint     := MISS;
         CARECL      : modelint     := MISS;
         CAREFL      : modelint     := MISS;
         CAREFR      : modelint     := MISS;
         CAREOT      : modelint     := MISS;
         CARERE      : modelint     := MISS;
         CHDDA       : modelint     := MISS;
         CHEARNS     : real         := MISS_R;
         CHINCDV     : real         := MISS_R;
         CHRINC      : real         := MISS_R;
         FSMLKVAL    : real         := MISS_R;
         FSMVAL      : real         := MISS_R;
         FWMLKVAL    : real         := MISS_R;
         HDAGECH     : modelint     := MISS;
         HOURAB      : modelint     := MISS;
         HOURAH      : modelint     := MISS;
         HOURCB      : modelint     := MISS;
         HOURCH      : modelint     := MISS;
         HOURCL      : modelint     := MISS;
         HOURFR      : modelint     := MISS;
         HOUROT      : modelint     := MISS;
         HOURRE      : modelint     := MISS;
         HOURTOT     : modelint     := MISS;
         HPERSON     : modelint     := MISS;
         IAGEGR2     : modelint     := MISS;
         IAGEGRP     : modelint     := MISS;
         RELHRP      : modelint     := MISS;
         TOTGNTCH    : real         := MISS_R;
         UPERSON     : modelint     := MISS;
         CDDATRE     : modelint     := MISS;
         CDISDIF9    : modelint     := MISS;
      end record;

   type Endowment_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         MORTSEQ     : modelint     := MISS;
         ENDOWSEQ    : modelint     := MISS;
         INCININT    : modelint     := MISS;
         MENPOLAM    : real         := MISS_R;
         MENPOLPD    : modelint     := MISS;
         MENSTYR     : modelint     := MISS;
         MONTH       : modelint     := MISS;
      end record;

   type ExtChild_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         BENUNIT     : modelint     := MISS;
         EXTSEQ      : modelint     := MISS;
         NHHAMT      : real         := MISS_R;
         NHHFEE      : modelint     := MISS;
         NHHINTRO    : modelint     := MISS;
         NHHPD       : modelint     := MISS;
         MONTH       : modelint     := MISS;
      end record;
   type GovPay_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         BENUNIT     : modelint     := MISS;
         PERSON      : modelint     := MISS;
         BENEFIT     : modelint     := MISS;
         GOVPAY      : modelint     := MISS;
         MONTH       : modelint     := MISS;
      end record;

   type Household_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         ACORN       : modelint     := MISS;
         BEDROOM     : modelint     := MISS;
         BENUNITS    : modelint     := MISS;
         BILLRATE    : modelint     := MISS;
         BUSROOM     : modelint     := MISS;
         CENTFUEL    : modelint     := MISS;
         CENTHEAT    : modelint     := MISS;
         CHARGE1     : modelint     := MISS;
         CHARGE2     : modelint     := MISS;
         CHARGE3     : modelint     := MISS;
         CHARGE4     : modelint     := MISS;
         CHARGE5     : modelint     := MISS;
         CHARGE6     : modelint     := MISS;
         CHARGE7     : modelint     := MISS;
         CHARGE8     : modelint     := MISS;
         CHARGE9     : modelint     := MISS;
         CHINS       : modelint     := MISS;
         CHRGAMT1    : real         := MISS_R;
         CHRGAMT2    : real         := MISS_R;
         CHRGAMT3    : real         := MISS_R;
         CHRGAMT4    : real         := MISS_R;
         CHRGAMT5    : real         := MISS_R;
         CHRGAMT6    : real         := MISS_R;
         CHRGAMT7    : real         := MISS_R;
         CHRGAMT8    : real         := MISS_R;
         CHRGAMT9    : real         := MISS_R;
         CHRGPD1     : modelint     := MISS;
         CHRGPD2     : modelint     := MISS;
         CHRGPD3     : modelint     := MISS;
         CHRGPD4     : modelint     := MISS;
         CHRGPD5     : modelint     := MISS;
         CHRGPD6     : modelint     := MISS;
         CHRGPD7     : modelint     := MISS;
         CHRGPD8     : modelint     := MISS;
         CHRGPD9     : modelint     := MISS;
         CONTV1      : modelint     := MISS;
         CONTV2      : modelint     := MISS;
         COVOTHS     : modelint     := MISS;
         CSEWAMT     : real         := MISS_R;
         CSEWAMT1    : real         := MISS_R;
         CT25D50D    : modelint     := MISS;
         CTAMT       : modelint     := MISS;
         CTANNUAL    : real         := MISS_R;
         CTBAND      : modelint     := MISS;
         CTBWAIT     : modelint     := MISS;
         CTCONDOC    : modelint     := MISS;
         CTDISC      : modelint     := MISS;
         CTINSTAL    : modelint     := MISS;
         CTLVBAND    : modelint     := MISS;
         CTLVCHK     : modelint     := MISS;
         CTREB       : modelint     := MISS;
         CTREBAMT    : modelint     := MISS;
         CTREBPD     : modelint     := MISS;
         CTTIME      : modelint     := MISS;
         CWATAMT     : modelint     := MISS;
         CWATAMT1    : modelint     := MISS;
         DATYRAGO    : modelint     := MISS;
         ENTRY1      : modelint     := MISS;
         ENTRY2      : modelint     := MISS;
         ENTRY3      : modelint     := MISS;
         ENTRY4      : modelint     := MISS;
         ESTRTANN    : real         := MISS_R;
         FLOOR       : modelint     := MISS;
         GIVEHELP    : modelint     := MISS;
         GOR         : modelint     := MISS;
         GVTREGN     : modelint     := MISS;
         HHLDR01     : modelint     := MISS;
         HHLDR02     : modelint     := MISS;
         HHLDR03     : modelint     := MISS;
         HHLDR04     : modelint     := MISS;
         HHLDR05     : modelint     := MISS;
         HHLDR06     : modelint     := MISS;
         HHLDR07     : modelint     := MISS;
         HHLDR08     : modelint     := MISS;
         HHLDR09     : modelint     := MISS;
         HHLDR10     : modelint     := MISS;
         HHLDR11     : modelint     := MISS;
         HHLDR12     : modelint     := MISS;
         HHLDR13     : modelint     := MISS;
         HHLDR14     : modelint     := MISS;
         HHLDR97     : modelint     := MISS;
         HHSTAT      : modelint     := MISS;
         HRPNUM      : modelint     := MISS;
         INTDATE     : modelint     := MISS;
         LAC         : modelint     := MISS;
         MAINACC     : modelint     := MISS;
         MNTHCODE    : modelint     := MISS;
         MODCON01    : modelint     := MISS;
         MODCON02    : modelint     := MISS;
         MODCON03    : modelint     := MISS;
         MODCON04    : modelint     := MISS;
         MODCON05    : modelint     := MISS;
         MODCON06    : modelint     := MISS;
         MODCON07    : modelint     := MISS;
         MODCON08    : modelint     := MISS;
         MODCON09    : modelint     := MISS;
         MODCON10    : modelint     := MISS;
         MODCON11    : modelint     := MISS;
         MODCON12    : modelint     := MISS;
         MODCON13    : modelint     := MISS;
         MODCON14    : modelint     := MISS;
         MONLIVE     : modelint     := MISS;
         NEEDHELP    : modelint     := MISS;
         NICOUN      : modelint     := MISS;
         NINRV       : real         := MISS_R;
         NIRATE      : real         := MISS_R;
         NORATE      : modelint     := MISS;
         ONBSROOM    : modelint     := MISS;
         ORGSEWAM    : real         := MISS_R;
         ORGWATAM    : real         := MISS_R;
         PAYRATE     : modelint     := MISS;
         PREMIUM     : modelint     := MISS;
         PTBSROOM    : modelint     := MISS;
         ROOMS       : modelint     := MISS;
         ROOMSHAR    : modelint     := MISS;
         RTANNUAL    : real         := MISS_R;
         RTCHECK     : real         := MISS_R;
         RTCONDOC    : modelint     := MISS;
         RTDEDUC     : modelint     := MISS;
         RTINSTAL    : modelint     := MISS;
         RTREB       : modelint     := MISS;
         RTREBAMT    : real         := MISS_R;
         RTREBPD     : modelint     := MISS;
         RTTIME      : modelint     := MISS;
         SAMPQTR     : modelint     := MISS;
         SCHMEAL     : modelint     := MISS;
         SCHMILK     : modelint     := MISS;
         SEWAMT      : real         := MISS_R;
         SEWANUL     : real         := MISS_R;
         SEWERPAY    : modelint     := MISS;
         SEWSEP      : modelint     := MISS;
         SEWTIME     : modelint     := MISS;
         SHELTER     : modelint     := MISS;
         SOBUY       : modelint     := MISS;
         SSTRTREG    : modelint     := MISS;
         STRAMT1     : real         := MISS_R;
         STRAMT2     : real         := MISS_R;
         STRCOV      : modelint     := MISS;
         STRMORT     : modelint     := MISS;
         STROTHS     : modelint     := MISS;
         STRPD1      : modelint     := MISS;
         STRPD2      : modelint     := MISS;
         SUBALLOW    : modelint     := MISS;
         SUBLET      : modelint     := MISS;
         SUBLETY     : modelint     := MISS;
         SUBRENT     : real         := MISS_R;
         TENURE      : modelint     := MISS;
         TOTADULT    : modelint     := MISS;
         TOTCHILD    : modelint     := MISS;
         TOTDEPDK    : modelint     := MISS;
         TVLIC       : modelint     := MISS;
         TYPEACC     : modelint     := MISS;
         USEVCL      : modelint     := MISS;
         WATAMT      : real         := MISS_R;
         WATANUL     : real         := MISS_R;
         WATERMET    : modelint     := MISS;
         WATERPAY    : modelint     := MISS;
         WATRB       : modelint     := MISS;
         WATTIME     : modelint     := MISS;
         WELFMILK    : modelint     := MISS;
         WHOCTB01    : modelint     := MISS;
         WHOCTB02    : modelint     := MISS;
         WHOCTB03    : modelint     := MISS;
         WHOCTB04    : modelint     := MISS;
         WHOCTB05    : modelint     := MISS;
         WHOCTB06    : modelint     := MISS;
         WHOCTB07    : modelint     := MISS;
         WHOCTB08    : modelint     := MISS;
         WHOCTB09    : modelint     := MISS;
         WHOCTB10    : modelint     := MISS;
         WHOCTB11    : modelint     := MISS;
         WHOCTB12    : modelint     := MISS;
         WHOCTB13    : modelint     := MISS;
         WHOCTB14    : modelint     := MISS;
         WHOCTBNS    : modelint     := MISS;
         WHOCTBOT    : modelint     := MISS;
         WHORSP01    : modelint     := MISS;
         WHORSP02    : modelint     := MISS;
         WHORSP03    : modelint     := MISS;
         WHORSP04    : modelint     := MISS;
         WHORSP05    : modelint     := MISS;
         WHORSP06    : modelint     := MISS;
         WHORSP07    : modelint     := MISS;
         WHORSP08    : modelint     := MISS;
         WHORSP09    : modelint     := MISS;
         WHORSP10    : modelint     := MISS;
         WHORSP11    : modelint     := MISS;
         WHORSP12    : modelint     := MISS;
         WHORSP13    : modelint     := MISS;
         WHORSP14    : modelint     := MISS;
         WHYNOCT     : modelint     := MISS;
         WMINTRO     : modelint     := MISS;
         WSEWAMT     : real         := MISS_R;
         WSEWANUL    : real         := MISS_R;
         WSEWTIME    : modelint     := MISS;
         YEARCODE    : modelint     := MISS;
         YEARLIVE    : modelint     := MISS;
         MONTH       : modelint     := MISS;
         ACTACCH     : modelint     := MISS;
         ADDDAHH     : modelint     := MISS;
         ADULTH      : modelint     := MISS;
         BASACTH     : modelint     := MISS;
         CHDDAHH     : modelint     := MISS;
         CURACTH     : modelint     := MISS;
         CWATAMTD    : modelint     := MISS;
         DEPCHLDH    : modelint     := MISS;
         EMP         : modelint     := MISS;
         EMPHRP      : modelint     := MISS;
         ENDOWPAY    : real         := MISS_R;
         EQUIVAHC    : real         := MISS_R;
         EQUIVBHC    : real         := MISS_R;
         FSBNDCTH    : modelint     := MISS;
         GBHSCOST    : modelint     := MISS;
         GEBACTH     : modelint     := MISS;
         GILTCTH     : modelint     := MISS;
         GROSS2      : modelint     := MISS;
         GROSS3      : modelint     := MISS;
         GROSSCT     : modelint     := MISS;
         HBENINC     : real         := MISS_R;
         HBINDHH     : modelint     := MISS;
         HCBAND      : modelint     := MISS;
         HDHHINC     : modelint     := MISS;
         HDTAX       : modelint     := MISS;
         HEARNS      : real         := MISS_R;
         HHAGEGR2    : modelint     := MISS;
         HHAGEGRP    : modelint     := MISS;
         HHCOMP      : modelint     := MISS;
         HHCOMPS     : modelint     := MISS;
         HHDISBEN    : real         := MISS_R;
         HHETHGR2    : modelint     := MISS;
         HHETHGRP    : modelint     := MISS;
         HHINC       : real         := MISS_R;
         HHINCBND    : modelint     := MISS;
         HHINV       : real         := MISS_R;
         HHIRBEN     : real         := MISS_R;
         HHKIDS      : modelint     := MISS;
         HHNIRBEN    : real         := MISS_R;
         HHOTHBEN    : real         := MISS_R;
         HHRENT      : real         := MISS_R;
         HHRINC      : real         := MISS_R;
         HHRPINC     : real         := MISS_R;
         HHSIZE      : modelint     := MISS;
         HHTVLIC     : real         := MISS_R;
         HHTXCRED    : real         := MISS_R;
         HOTHINC     : real         := MISS_R;
         HPENINC     : real         := MISS_R;
         HRBAND      : modelint     := MISS;
         HSEINC      : real         := MISS_R;
         ISACTH      : modelint     := MISS;
         LONDON      : modelint     := MISS;
         MORTCOST    : real         := MISS_R;
         MORTINT     : real         := MISS_R;
         MORTPAY     : real         := MISS_R;
         NDDCTB      : real         := MISS_R;
         NDDISHC     : real         := MISS_R;
         NIHSCOST    : real         := MISS_R;
         NSBOCTH     : modelint     := MISS;
         OTBSCTH     : modelint     := MISS;
         PACCTYPE    : modelint     := MISS;
         PENAGE      : modelint     := MISS;
         PENHRP      : modelint     := MISS;
         PEPSCTH     : modelint     := MISS;
         POACCTH     : modelint     := MISS;
         PRBOCTH     : modelint     := MISS;
         PTENTYP2    : modelint     := MISS;
         SAYECTH     : modelint     := MISS;
         SCLBCTH     : modelint     := MISS;
         SERVPAY     : real         := MISS_R;
         SICK        : modelint     := MISS;
         SICKHRP     : modelint     := MISS;
         SSCTH       : modelint     := MISS;
         STRUINS     : real         := MISS_R;
         STSHCTH     : modelint     := MISS;
         TENTYP2     : modelint     := MISS;
         TESSCTH     : modelint     := MISS;
         TUHHRENT    : real         := MISS_R;
         TUWATSEW    : real         := MISS_R;
         UNTRCTH     : modelint     := MISS;
         WATSEWRT    : real         := MISS_R;
         ACORNEW     : modelint     := MISS;
         CRUNACH     : modelint     := MISS;
         ENOMORTH    : modelint     := MISS;
      end record;

   type Insurance_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         INSSEQ      : modelint     := MISS;
         NUMPOLS1    : modelint     := MISS;
         NUMPOLS2    : modelint     := MISS;
         NUMPOLS3    : modelint     := MISS;
         NUMPOLS4    : modelint     := MISS;
         NUMPOLS5    : modelint     := MISS;
         NUMPOLS6    : modelint     := MISS;
         NUMPOLS7    : modelint     := MISS;
         NUMPOLS8    : modelint     := MISS;
         NUMPOLS9    : modelint     := MISS;
         POLAMT      : real         := MISS_R;
         POLMORE     : modelint     := MISS;
         POLPAY      : modelint     := MISS;
         POLPD       : modelint     := MISS;
         MONTH       : modelint     := MISS;
      end record;

   type Job_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         BENUNIT     : modelint     := MISS;
         PERSON      : modelint     := MISS;
         JOBTYPE     : modelint     := MISS;
         AGREEHRS    : modelint     := MISS;
         BONAMT1     : real         := MISS_R;
         BONAMT2     : real         := MISS_R;
         BONAMT3     : real         := MISS_R;
         BONAMT4     : real         := MISS_R;
         BONAMT5     : real         := MISS_R;
         BONAMT6     : real         := MISS_R;
         BONTAX1     : modelint     := MISS;
         BONTAX2     : modelint     := MISS;
         BONTAX3     : modelint     := MISS;
         BONTAX4     : modelint     := MISS;
         BONTAX5     : modelint     := MISS;
         BONTAX6     : modelint     := MISS;
         BONUS       : modelint     := MISS;
         BUSACCTS    : modelint     := MISS;
         CHECKTAX    : modelint     := MISS;
         CHKINCOM    : modelint     := MISS;
         DEDOTH      : real         := MISS_R;
         DEDUC1      : real         := MISS_R;
         DEDUC2      : real         := MISS_R;
         DEDUC3      : real         := MISS_R;
         DEDUC4      : real         := MISS_R;
         DEDUC5      : real         := MISS_R;
         DEDUC6      : real         := MISS_R;
         DEDUC7      : real         := MISS_R;
         DEDUC8      : real         := MISS_R;
         DIRCTR      : modelint     := MISS;
         DIRNI       : modelint     := MISS;
         DVTOTHRU    : modelint     := MISS;
         DVUSHR      : real         := MISS_R;
         EMPANY      : modelint     := MISS;
         EMPOWN      : modelint     := MISS;
         ETYPE       : modelint     := MISS;
         EVEROT      : modelint     := MISS;
         FTPT        : modelint     := MISS;
         GRSOFAR     : real         := MISS_R;
         GRWAGE      : real         := MISS_R;
         GRWAGPD     : modelint     := MISS;
         HHA1        : real         := MISS_R;
         HHA2        : real         := MISS_R;
         HHA3        : real         := MISS_R;
         HHC1        : modelint     := MISS;
         HHC2        : modelint     := MISS;
         HHC3        : modelint     := MISS;
         HOHINC      : modelint     := MISS;
         INCLPAY1    : modelint     := MISS;
         INCLPAY2    : modelint     := MISS;
         INCLPAY3    : modelint     := MISS;
         INCLPAY4    : modelint     := MISS;
         INCLPAY5    : modelint     := MISS;
         INCLPAY6    : modelint     := MISS;
         INKIND01    : modelint     := MISS;
         INKIND02    : modelint     := MISS;
         INKIND03    : modelint     := MISS;
         INKIND04    : modelint     := MISS;
         INKIND05    : modelint     := MISS;
         INKIND06    : modelint     := MISS;
         INKIND07    : modelint     := MISS;
         INKIND08    : modelint     := MISS;
         INKIND09    : modelint     := MISS;
         INKIND10    : modelint     := MISS;
         INKIND11    : modelint     := MISS;
         INSTYPE1    : modelint     := MISS;
         INSTYPE2    : modelint     := MISS;
         JOBBUS      : modelint     := MISS;
         LIKEHR      : modelint     := MISS;
         MADEMP      : modelint     := MISS;
         MATEMP      : modelint     := MISS;
         MATSTP      : modelint     := MISS;
         MILEAMT     : real         := MISS_R;
         MOTAMT      : real         := MISS_R;
         NATINS      : real         := MISS_R;
         NATURE      : modelint     := MISS;
         NIDAMT      : real         := MISS_R;
         NIDPD       : modelint     := MISS;
         NMCHC       : modelint     := MISS;
         NMPER       : modelint     := MISS;
         NOMOR1      : modelint     := MISS;
         NOMOR2      : modelint     := MISS;
         NOMOR3      : modelint     := MISS;
         NUMEMP      : modelint     := MISS;
         OTHDED1     : modelint     := MISS;
         OTHDED2     : modelint     := MISS;
         OTHDED3     : modelint     := MISS;
         OTHDED4     : modelint     := MISS;
         OTHDED5     : modelint     := MISS;
         OTHDED6     : modelint     := MISS;
         OTHDED7     : modelint     := MISS;
         OTHDED8     : modelint     := MISS;
         OTHDED9     : modelint     := MISS;
         OWNAMT      : real         := MISS_R;
         OWNOTAMT    : real         := MISS_R;
         OWNOTHER    : modelint     := MISS;
         OWNSUM      : modelint     := MISS;
         PAYAMT      : real         := MISS_R;
         PAYDAT      : modelint     := MISS;
         PAYE        : real         := MISS_R;
         PAYPD       : modelint     := MISS;
         PAYSLIP     : modelint     := MISS;
         PAYUSL      : modelint     := MISS;
         POTHR       : real         := MISS_R;
         PRBEFORE    : real         := MISS_R;
         PROFDOCS    : modelint     := MISS;
         PROFIT1     : real         := MISS_R;
         PROFIT2     : modelint     := MISS;
         PROFNI      : modelint     := MISS;
         PROFTAX     : modelint     := MISS;
         RSPOTH      : modelint     := MISS;
         SE1         : modelint     := MISS;
         SE2         : modelint     := MISS;
         SEEND       : modelint     := MISS;
         SEINCAMT    : real         := MISS_R;
         SEINCWM     : modelint     := MISS;
         SELWKS      : modelint     := MISS;
         SENIIAMT    : real         := MISS_R;
         SENIINC     : modelint     := MISS;
         SENILAMT    : real         := MISS_R;
         SENILUMP    : modelint     := MISS;
         SENIRAMT    : real         := MISS_R;
         SENIREG     : modelint     := MISS;
         SENIRPD     : modelint     := MISS;
         SETAX       : modelint     := MISS;
         SETAXAMT    : real         := MISS_R;
         SMPAMT      : real         := MISS_R;
         SMPRATE     : modelint     := MISS;
         SOLE        : modelint     := MISS;
         SSPAMT      : real         := MISS_R;
         TAXAMT      : real         := MISS_R;
         TAXDAMT     : real         := MISS_R;
         TAXDPD      : modelint     := MISS;
         TOTUS1      : real         := MISS_R;
         UBONAMT     : real         := MISS_R;
         UBONINC     : modelint     := MISS;
         UDEDUC1     : real         := MISS_R;
         UDEDUC2     : real         := MISS_R;
         UDEDUC3     : real         := MISS_R;
         UDEDUC4     : real         := MISS_R;
         UDEDUC5     : real         := MISS_R;
         UDEDUC6     : real         := MISS_R;
         UDEDUC7     : real         := MISS_R;
         UDEDUC8     : real         := MISS_R;
         UGROSS      : real         := MISS_R;
         UINCPAY1    : modelint     := MISS;
         UINCPAY2    : modelint     := MISS;
         UINCPAY3    : modelint     := MISS;
         UINCPAY4    : modelint     := MISS;
         UINCPAY5    : modelint     := MISS;
         UINCPAY6    : modelint     := MISS;
         UMILEAMT    : real         := MISS_R;
         UMOTAMT     : real         := MISS_R;
         UNETT       : real         := MISS_R;
         UOTHDED1    : modelint     := MISS;
         UOTHDED2    : modelint     := MISS;
         UOTHDED3    : modelint     := MISS;
         UOTHDED4    : modelint     := MISS;
         UOTHDED5    : modelint     := MISS;
         UOTHDED6    : modelint     := MISS;
         UOTHDED7    : modelint     := MISS;
         UOTHDED8    : modelint     := MISS;
         UOTHDED9    : modelint     := MISS;
         UOTHDTOT    : real         := MISS_R;
         UOTHR       : real         := MISS_R;
         UPD         : modelint     := MISS;
         USMPAMT     : real         := MISS_R;
         USMPRATE    : modelint     := MISS;
         USSPAMT     : real         := MISS_R;
         USUHR       : real         := MISS_R;
         UTAXAMT     : real         := MISS_R;
         WATDID      : modelint     := MISS;
         WATPREV     : modelint     := MISS;
         WHERE       : modelint     := MISS;
         WHYNOPRO    : modelint     := MISS;
         WHYNOU01    : modelint     := MISS;
         WHYNOU02    : modelint     := MISS;
         WHYNOU03    : modelint     := MISS;
         WHYNOU04    : modelint     := MISS;
         WHYNOU05    : modelint     := MISS;
         WHYNOU06    : modelint     := MISS;
         WHYNOU07    : modelint     := MISS;
         WHYNOU08    : modelint     := MISS;
         WHYNOU09    : modelint     := MISS;
         WHYNOU10    : modelint     := MISS;
         WHYNOU11    : modelint     := MISS;
         WORKACC     : modelint     := MISS;
         WORKMTH     : modelint     := MISS;
         WORKYR      : modelint     := MISS;
         MONTH       : modelint     := MISS;
         HDQHRS      : modelint     := MISS;
         JOBHOURS    : real         := MISS_R;
         SSPSMPFG    : modelint     := MISS;
         UGRSPAY     : real         := MISS_R;
         INCLPAY7    : modelint     := MISS;
         INCLPAY8    : modelint     := MISS;
         PAPERIOD    : modelint     := MISS;
         PPPERIOD    : modelint     := MISS;
         SAPAMT      : modelint     := MISS;
         SPPAMT      : real         := MISS_R;
         UINCPAY7    : modelint     := MISS;
         UINCPAY8    : modelint     := MISS;
         USAPAMT     : modelint     := MISS;
         USPPAMT     : real         := MISS_R;
      end record;

   type Maint_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         BENUNIT     : modelint     := MISS;
         PERSON      : modelint     := MISS;
         MAINTSEQ    : modelint     := MISS;
         M           : modelint     := MISS;
         MRAGE       : modelint     := MISS;
         MRAMT       : real         := MISS_R;
         MRCHWHY1    : modelint     := MISS;
         MRCHWHY2    : modelint     := MISS;
         MRCHWHY3    : modelint     := MISS;
         MRCHWHY4    : modelint     := MISS;
         MRCHWHY5    : modelint     := MISS;
         MRCHWHY6    : modelint     := MISS;
         MRCHWHY7    : modelint     := MISS;
         MRCHWHY8    : modelint     := MISS;
         MRCHWHY9    : modelint     := MISS;
         MRCT        : modelint     := MISS;
         MRKID       : modelint     := MISS;
         MRPD        : modelint     := MISS;
         MRR         : modelint     := MISS;
         MRUAMT      : real         := MISS_R;
         MRUPD       : modelint     := MISS;
         MRUS        : modelint     := MISS;
         MRV         : modelint     := MISS;
         MONTH       : modelint     := MISS;
      end record;

   type MortCont_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         MORTSEQ     : modelint     := MISS;
         CONTSEQ     : modelint     := MISS;
         OUTSAMT     : real         := MISS_R;
         OUTSINCL    : modelint     := MISS;
         OUTSPAY     : modelint     := MISS;
         OUTSPD      : modelint     := MISS;
         MONTH       : modelint     := MISS;
      end record;

   type Mortgage_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         MORTSEQ     : modelint     := MISS;
         BORAMTDK    : modelint     := MISS;
         BORRAMT     : real         := MISS_R;
         ENDWPRI1    : modelint     := MISS;
         ENDWPRI2    : modelint     := MISS;
         ENDWPRI3    : modelint     := MISS;
         ENDWPRI4    : modelint     := MISS;
         EXRENT      : modelint     := MISS;
         INCMINC1    : modelint     := MISS;
         INCMINC2    : modelint     := MISS;
         INCMINC3    : modelint     := MISS;
         INCMP1      : modelint     := MISS;
         INCMP2      : modelint     := MISS;
         INCMP3      : modelint     := MISS;
         INCMPAM1    : real         := MISS_R;
         INCMPAM2    : real         := MISS_R;
         INCMPAM3    : real         := MISS_R;
         INCMPPD1    : modelint     := MISS;
         INCMPPD2    : modelint     := MISS;
         INCMPPD3    : modelint     := MISS;
         INCMSTY1    : modelint     := MISS;
         INCMSTY2    : modelint     := MISS;
         INCMSTY3    : modelint     := MISS;
         INTPRPAY    : real         := MISS_R;
         INTPRPD     : modelint     := MISS;
         INTRU       : real         := MISS_R;
         INTRUPD     : modelint     := MISS;
         INTRUS      : modelint     := MISS;
         LOAN2Y      : modelint     := MISS;
         LOANYEAR    : modelint     := MISS;
         MENPOL      : modelint     := MISS;
         MORALL      : modelint     := MISS;
         MORFLC      : modelint     := MISS;
         MORINPAY    : real         := MISS_R;
         MORINPD     : modelint     := MISS;
         MORINUS     : modelint     := MISS;
         MORTEND     : modelint     := MISS;
         MORTLEFT    : real         := MISS_R;
         MORTPROT    : modelint     := MISS;
         MORTTYPE    : modelint     := MISS;
         MORUPD      : modelint     := MISS;
         MORUS       : real         := MISS_R;
         MPCOVER1    : modelint     := MISS;
         MPCOVER2    : modelint     := MISS;
         MPCOVER3    : modelint     := MISS;
         MPOLNO      : modelint     := MISS;
         OUTSMORT    : modelint     := MISS;
         RENTFROM    : modelint     := MISS;
         RMAMT       : real         := MISS_R;
         RMORT       : modelint     := MISS;
         RMORTYR     : modelint     := MISS;
         RMPUR001    : modelint     := MISS;
         RMPUR002    : modelint     := MISS;
         RMPUR003    : modelint     := MISS;
         RMPUR004    : modelint     := MISS;
         RMPUR005    : modelint     := MISS;
         RMPUR006    : modelint     := MISS;
         RMPUR007    : modelint     := MISS;
         RMPUR008    : modelint     := MISS;
         MONTH       : modelint     := MISS;
         ENDWPRI5    : modelint     := MISS;
      end record;

   type OddJob_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         BENUNIT     : modelint     := MISS;
         PERSON      : modelint     := MISS;
         ODDTYPE     : modelint     := MISS;
         ODDSEQ      : modelint     := MISS;
         OJAMT       : real         := MISS_R;
         OJNOW       : modelint     := MISS;
         OJREG       : modelint     := MISS;
         MONTH       : modelint     := MISS;
      end record;
   type Owner_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         BUYYEAR     : modelint     := MISS;
         OTHMORT1    : modelint     := MISS;
         OTHMORT2    : modelint     := MISS;
         OTHMORT3    : modelint     := MISS;
         OTHPUR1     : modelint     := MISS;
         OTHPUR2     : modelint     := MISS;
         OTHPUR3     : modelint     := MISS;
         OTHPUR31    : modelint     := MISS;
         OTHPUR32    : modelint     := MISS;
         OTHPUR33    : modelint     := MISS;
         OTHPUR34    : modelint     := MISS;
         OTHPUR35    : modelint     := MISS;
         OTHPUR36    : modelint     := MISS;
         OTHPUR37    : modelint     := MISS;
         OTHPUR4     : modelint     := MISS;
         OTHPUR5     : modelint     := MISS;
         OTHPUR6     : modelint     := MISS;
         OTHPUR7     : modelint     := MISS;
         PURCAMT     : real         := MISS_R;
         PURCLOAN    : modelint     := MISS;
         MONTH       : modelint     := MISS;
      end record;

   type PenAmt_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         BENUNIT     : modelint     := MISS;
         PERSON      : modelint     := MISS;
         BENEFIT     : modelint     := MISS;
         AMTTYPE     : modelint     := MISS;
         PENQ        : real         := MISS_R;
         MONTH       : modelint     := MISS;
      end record;

   type PenProv_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         BENUNIT     : modelint     := MISS;
         PERSON      : modelint     := MISS;
         STEMPPAY    : modelint     := MISS;
         PROVSEQ     : modelint     := MISS;
         EPLONG      : modelint     := MISS;
         EPTYPE      : modelint     := MISS;
         KEEPPEN     : modelint     := MISS;
         OPGOV       : modelint     := MISS;
         PENAMT      : real         := MISS_R;
         PENAMTPD    : modelint     := MISS;
         PENCON      : modelint     := MISS;
         PENDAT      : modelint     := MISS;
         PENGOV      : modelint     := MISS;
         PENHELP     : modelint     := MISS;
         PENMORT     : modelint     := MISS;
         SPWHO       : modelint     := MISS;
         MONTH       : modelint     := MISS;
      end record;
   type Pension_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         BENUNIT     : modelint     := MISS;
         PERSON      : modelint     := MISS;
         PENSEQ      : modelint     := MISS;
         ANOTHER     : modelint     := MISS;
         PENOTH      : modelint     := MISS;
         PENPAY      : real         := MISS_R;
         PENPD       : modelint     := MISS;
         PENTAX      : modelint     := MISS;
         PENTYPE     : modelint     := MISS;
         POAMT       : real         := MISS_R;
         POINC       : modelint     := MISS;
         POSOUR      : modelint     := MISS;
         PTAMT       : real         := MISS_R;
         PTINC       : modelint     := MISS;
         TRIGHTS     : modelint     := MISS;
         MONTH       : modelint     := MISS;
      end record;
   type RentCont_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         RENTSEQ     : modelint     := MISS;
         ACCAMT      : real         := MISS_R;
         ACCCHK      : modelint     := MISS;
         ACCPAY      : modelint     := MISS;
         ACCPD       : modelint     := MISS;
         MONTH       : modelint     := MISS;
      end record;
   type Renter_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         ACCJBP01    : modelint     := MISS;
         ACCJBP02    : modelint     := MISS;
         ACCJBP03    : modelint     := MISS;
         ACCJBP04    : modelint     := MISS;
         ACCJBP05    : modelint     := MISS;
         ACCJBP06    : modelint     := MISS;
         ACCJBP07    : modelint     := MISS;
         ACCJBP08    : modelint     := MISS;
         ACCJBP09    : modelint     := MISS;
         ACCJBP10    : modelint     := MISS;
         ACCJBP11    : modelint     := MISS;
         ACCJBP12    : modelint     := MISS;
         ACCJBP13    : modelint     := MISS;
         ACCJBP14    : modelint     := MISS;
         ACCJOB      : modelint     := MISS;
         ACCNONHH    : modelint     := MISS;
         CTRACT      : modelint     := MISS;
         ELIGAMT     : real         := MISS_R;
         ELIGPD      : modelint     := MISS;
         FAIRRENT    : modelint     := MISS;
         FURNISH     : modelint     := MISS;
         HBENAMT     : real         := MISS_R;
         HBENCHK     : modelint     := MISS;
         HBENEFIT    : modelint     := MISS;
         HBENPD      : modelint     := MISS;
         HBENWAIT    : modelint     := MISS;
         HBWEEKS     : modelint     := MISS;
         LANDLORD    : modelint     := MISS;
         NIYSTART    : modelint     := MISS;
         OTHWAY      : modelint     := MISS;
         REBATE      : modelint     := MISS;
         RENT        : real         := MISS_R;
         RENTDK      : modelint     := MISS;
         RENTDOC     : modelint     := MISS;
         RENTFULL    : real         := MISS_R;
         RENTHOL     : modelint     := MISS;
         RENTPD      : modelint     := MISS;
         RESLL       : modelint     := MISS;
         RESLL2      : modelint     := MISS;
         SERINC1     : modelint     := MISS;
         SERINC2     : modelint     := MISS;
         SERINC3     : modelint     := MISS;
         SERINC4     : modelint     := MISS;
         SERINC5     : modelint     := MISS;
         SHORT1      : modelint     := MISS;
         SHORT2      : modelint     := MISS;
         WEEKHOL     : modelint     := MISS;
         WSINC       : modelint     := MISS;
         WSINCAMT    : real         := MISS_R;
         YSTARTR     : modelint     := MISS;
         MONTH       : modelint     := MISS;
         HBYEARS     : modelint     := MISS;
         LOWSHORT    : modelint     := MISS;
         OTHTYPE     : modelint     := MISS;
         TENTYPE     : modelint     := MISS;
      end record;
   type Vehicle_Rec is
      record
         SERNUM      : SernumString := (others => ' ');
         hh_sequence : modelint     := MISS;
         VEHSEQ      : modelint     := MISS;
         VEHIC       : modelint     := MISS;
         VEHOWN      : modelint     := MISS;
         MONTH       : modelint     := MISS;
      end record;

   type Pension_Array is array (Pension_Count) of Pension_Rec;

   type PenProv_Array is array (Pension_Count) of PenProv_Rec;
   type PenAmt_Array is array (Pension_Count) of PenAmt_Rec;

   type Account_Array is array (Account_Count) of Account_Rec;

   type Assets_Array is array (1 .. MAX_NUM_ASSETS) of Asset_Rec;

   type Benefit_Array is array (1 .. MAX_NUM_BENEFITS) of Benefit_Rec;

   type Care_Array is array (1 .. MAX_NUM_CARES) of Care_Rec;

   type Endowment_Array is array (1 .. MAX_NUM_ENDOWMENTS) of Endowment_Rec;

   type ExtChild_Array is array (1 .. MAX_NUM_EXT_CHILD) of ExtChild_Rec;

   type GovPay_Array is array (1 .. MAX_NUM_GOV_PAY) of GovPay_Rec;

   type Insurance_Array is array (1 .. MAX_NUM_INSURANCES) of Insurance_Rec;

   type Maint_Array is array (1 .. MAX_NUM_MAINTS) of Maint_Rec;

   type MortCont_Array is array (1 .. MAX_NUM_MORT_CONTS) of MortCont_Rec;

   type Mortgage_Array is array (1 .. MAX_NUM_MORTGAGES) of Mortgage_Rec;

   type OddJob_Array is array (1 .. MAX_NUM_ODD_JOBS) of OddJob_Rec;

   type RentCont_Array is array (1 .. MAX_NUM_RENT_CONTS) of RentCont_Rec;

   type Vehicle_Array is array (1 .. MAX_NUM_VEHICLES) of Vehicle_Rec;

   type Job_Array is array (1 .. MAX_NUM_JOBS) of Job_Rec;

   type Raw_Adult is
      record
         adult : Adult_Rec;

         numJobs : Job_Count := 0;
         jobs    : Job_Array;

         numAccounts : Account_Count := 0;
         accounts    : Account_Array;

         numAssets : Asset_Count := 0;
         assets    : Assets_Array;

         numBenefits : Benefit_Count := 0;
         benefits    : Benefit_Array;

         numGovpays : GovPay_Count := 0;
         govpay     : GovPay_Array;

         numMaintenances : Maint_Count := 0;
         maintenances    : Maint_Array;

         numOddJobs : OddJob_Count := 0;
         oddJobs    : OddJob_Array;

         numpensions : Pension_Count := 0;
         pensions    : Pension_Array;

         numPenProvs : Pension_Count := 0;
         penprovs    : PenProv_Array;

         numPenAmts : Pension_Count := 0;
         penamts    : PenAmt_Array;
      end record;

   type Raw_Child is
      record
         child : Child_Rec;
      end record;

   type Child_Array is array (1 .. MAX_NUM_CHILDREN) of Raw_Child;
   type Adults_Array is array (1 .. 2) of Raw_Adult;

   type Raw_Benefit_unit is
      record
         benunit : Benunit_Rec;

         numAdults : Adult_Count := 0;
         adults    : Adults_Array;

         numCares : Care_Count := 0;
         cares    : Care_Array;

         num_children : Child_Count := 0;
         children    : Child_Array;

         numExtChildren : Child_Count := 0;
         extchild       : ExtChild_Array;
      end record;

   type BenUnit_Array is array (1 .. MAX_NUM_BENEFIT_UNITS) of Raw_Benefit_unit;

   type Raw_Household is
      record
         household : Household_Rec;
         admin     : Admin_Rec;

         renter : Renter_Rec;
         owner  : Owner_Rec;

         numBenUnits : Integer := 0;
         benunits    : BenUnit_Array;

         numVehicles : Integer := 0;
         vehicles    : Vehicle_Array;

         numEndowments : Integer := 0;
         endowments    : Endowment_Array;

         numInsurances : Integer := 0;
         insurance     : Insurance_Array;

         numMortConts : Integer := 0;
         mortCont     : MortCont_Array;

         numMortgages : Integer := 0;
         mortgages    : Mortgage_Array;

         numRentConts : Integer := 0;
         rentCont     : RentCont_Array;
      end record;

   type RecordComponents is (
      adultRec,
      accountRec,
      adminRec,
      assetRec,
      benefitRec,
      benunitRec,
      careRec,
      childRec,
      endowmentRec,
      extChildRec,
      govPayRec,
      householdRec,
      insuranceRec,
      jobRec,
      maintRec,
      mortContRec,
      mortgageRec,
      oddJobRec,
      ownerRec,
      penprovRec,
      penAmtRec,
      pensionRec,
      rentContRec,
      renterRec,
      vehicleRec);

   type ComponentPointers is array (RecordComponents) of RecordIndicator;

   type Index_Rec is
      record
         SERNUM   : SernumString := (others => ' ');
         pointers : ComponentPointers;

      end record;

end raw_frs;
