with Ada.Strings.Unbounded;

package test_enum is
 package SU   renames Ada.Strings.Unbounded;
	-- test_names : constant :=
   type MyEnum is ( A, B, C );

   for MyEnum use ( A => 3, B => 7, C => 13 );

   MyEnumStr : constant array ( MyEnum ) of SU.Unbounded_String := (A=>SU.To_Unbounded_String("A 1234"),
                                                                    B=>SU.To_Unbounded_String("N  xx"),
                                                                    C=>SU.To_Unbounded_String(""));



   type Benefits is (
     dla_mobility,
     child_benefit,
     pension_credit,
     retirement_pension_opp,
     widows_pension_bereavement_allowance,
     widowed_mothers_widowed_parents_allowance,
     war_disablement_pension,
     war_widows_widowers_pension,
     severe_disability_allowance,
     attendence_allowance,
     invalid_care_allowance,
     jobseekers_allowance,
     industrial_injury_disablement_benefit,
     incapacity_benefit,
     income_support,
     new_deal,
     maternity_allowance,
     maternity_grant_from_social_fund,
     funeral_grant_from_social_fund,
     community_care_grant_from_social_fund,
     back_to_work_bonus_received,
     back_to_work_bonus_accrued,
     any_other_ni_or_state_benefit,
     trade_union_sick_strike_pay,
     friendly_society_benefits,
     private_sickness_scheme_benefits,
     accident_insurance_scheme_benefits,
     hospital_savings_scheme_benefits,
     government_training_allowances,
     guardians_allowance,
     social_fund_loan_budgeting,
     social_fund_loan_crisis,
     future_dla_self_care,
     future_dla_mobility,
     future_attendance_allowance,
     rcpt_last_6m_work_search_premium,
     rcpt_last_6m_in_work_credit,
     rcpt_last_6m_return_to_work_credit,
     rcpt_last_6_months_child_maintenance_bonus_premium,
     lone_parent_benefit_run_on,
     widows_payment,
     unemployment_redundancy_insurance,
     winter_fuel_payments,
     dwp_third_party_payments_isa,
     dwp_third_party_payments_jsa,
     hb_only_or_separately,
     ctb_only_or_separately,
     hb_ctb_paid_together,
     permanent_health_insurance,
     any_other_sickness_insurance,
     critical_illness_cover,
     working_tax_credit,
     child_tax_credit,
     working_tax_credit_lump_sum,
     child_tax_credit_lump_sum
);

   for Benefits use (
     dla_mobility => 2,
     child_benefit => 3,
     pension_credit => 4,
     retirement_pension_opp => 5,
     widows_pension_bereavement_allowance => 6,
     widowed_mothers_widowed_parents_allowance => 7,
     war_disablement_pension => 8,
     war_widows_widowers_pension => 9,
     severe_disability_allowance => 10,
     attendence_allowance => 12,
     invalid_care_allowance => 13,
     jobseekers_allowance => 14,
     industrial_injury_disablement_benefit => 15,
     incapacity_benefit => 17,
     income_support => 19,
     new_deal => 20,
     maternity_allowance => 21,
     maternity_grant_from_social_fund => 22,
     funeral_grant_from_social_fund => 24,
     community_care_grant_from_social_fund => 25,
     back_to_work_bonus_received => 26,
     back_to_work_bonus_accrued => 27,
     any_other_ni_or_state_benefit => 30,
     trade_union_sick_strike_pay => 31,
     friendly_society_benefits => 32,
     private_sickness_scheme_benefits => 33,
     accident_insurance_scheme_benefits => 34,
     hospital_savings_scheme_benefits => 35,
     government_training_allowances => 36,
     guardians_allowance => 37,
     social_fund_loan_budgeting => 39,
     social_fund_loan_crisis => 40,
     future_dla_self_care => 42,
     future_dla_mobility => 43,
     future_attendance_allowance => 44,
     rcpt_last_6m_work_search_premium => 45,
     rcpt_last_6m_in_work_credit => 46,
     rcpt_last_6m_return_to_work_credit => 47,
     rcpt_last_6_months_child_maintenance_bonus_premium => 51,
     lone_parent_benefit_run_on => 52,
     widows_payment => 60,
     unemployment_redundancy_insurance => 61,
     winter_fuel_payments => 62,
     dwp_third_party_payments_isa => 65,
     dwp_third_party_payments_jsa => 66,
     hb_only_or_separately => 78,
     ctb_only_or_separately => 79,
     hb_ctb_paid_together => 80,
     permanent_health_insurance => 81,
     any_other_sickness_insurance => 82,
     critical_illness_cover => 83,
     working_tax_credit => 90,
     child_tax_credit => 91,
     working_tax_credit_lump_sum => 92,
     child_tax_credit_lump_sum => 93
                    );

   Benefits_Str : constant array ( Benefits ) of SU.Unbounded_String := (
       dla_mobility => SU.To_Unbounded_String("DLA(mobility)"),
       child_benefit => SU.To_Unbounded_String("Child Benefit"),
       pension_credit => SU.To_Unbounded_String("Pension credit"),
       retirement_pension_opp => SU.To_Unbounded_String("Retirement Pension /OPP"),
       widows_pension_bereavement_allowance => SU.To_Unbounded_String("Widow's Pension/Bereavement Allowance"),
       widowed_mothers_widowed_parents_allowance => SU.To_Unbounded_String("Widowed Mothers/Widowed Parents Allowance"),
       war_disablement_pension => SU.To_Unbounded_String("War Disablement Pension"),
       war_widows_widowers_pension => SU.To_Unbounded_String("War Widow's/Widower's Pension"),
       severe_disability_allowance => SU.To_Unbounded_String("Severe Disability Allowance"),
       attendence_allowance => SU.To_Unbounded_String("Attendence Allowance"),
       invalid_care_allowance => SU.To_Unbounded_String("Invalid Care Allowance"),
       jobseekers_allowance => SU.To_Unbounded_String("Jobseeker's Allowance"),
       industrial_injury_disablement_benefit => SU.To_Unbounded_String("Industrial Injury Disablement Benefit"),
       incapacity_benefit => SU.To_Unbounded_String("Incapacity Benefit"),
       income_support => SU.To_Unbounded_String("Income Support"),
       new_deal => SU.To_Unbounded_String("New Deal"),
       maternity_allowance => SU.To_Unbounded_String("Maternity Allowance"),
       maternity_grant_from_social_fund => SU.To_Unbounded_String("Maternity Grant from Social Fund"),
       funeral_grant_from_social_fund => SU.To_Unbounded_String("Funeral Grant from Social Fund"),
       community_care_grant_from_social_fund => SU.To_Unbounded_String("Community Care grant from Social Fund"),
       back_to_work_bonus_received => SU.To_Unbounded_String("Back to_Work_Bonus__received"),
       back_to_work_bonus_accrued => SU.To_Unbounded_String("Back to Work Bonus (accrued)"),
       any_other_ni_or_state_benefit => SU.To_Unbounded_String("Any other NI or State benefit"),
       trade_union_sick_strike_pay => SU.To_Unbounded_String("Trade Union sick/strike pay"),
       friendly_society_benefits => SU.To_Unbounded_String("Friendly Society Benefits"),
       private_sickness_scheme_benefits => SU.To_Unbounded_String("Private sickness scheme benefits"),
       accident_insurance_scheme_benefits => SU.To_Unbounded_String("Accident insurance scheme benefits"),
       hospital_savings_scheme_benefits => SU.To_Unbounded_String("Hospital savings scheme benefits"),
       government_training_allowances => SU.To_Unbounded_String("Government training allowances"),
       guardians_allowance => SU.To_Unbounded_String("Guardians Allowance"),
       social_fund_loan_budgeting => SU.To_Unbounded_String("Social Fund Loan:Budgeting"),
       social_fund_loan_crisis => SU.To_Unbounded_String("Social Fund Loan:Crisis"),
       future_dla_self_care => SU.To_Unbounded_String("Future: DLA Self Care"),
       future_dla_mobility => SU.To_Unbounded_String("Future: DLA Mobility"),
       future_attendance_allowance => SU.To_Unbounded_String("Future: Attendance Allowance"),
       rcpt_last_6m_work_search_premium => SU.To_Unbounded_String("Rcpt last 6m: Work-Search Premium"),
       rcpt_last_6m_in_work_credit => SU.To_Unbounded_String("Rcpt last 6m: In-work credit"),
       rcpt_last_6m_return_to_work_credit => SU.To_Unbounded_String("Rcpt last 6m: Return to work credit"),
       rcpt_last_6_months_child_maintenance_bonus_premium => SU.To_Unbounded_String("Rcpt last 6 months Child Maintenance Bonus/Premium"),
       lone_parent_benefit_run_on => SU.To_Unbounded_String("Lone Parent Benefit run-on"),
       widows_payment => SU.To_Unbounded_String("Widow's Payment"),
       unemployment_redundancy_insurance => SU.To_Unbounded_String("Unemployment/Redundancy Insurance"),
       winter_fuel_payments => SU.To_Unbounded_String("Winter Fuel Payments"),
       dwp_third_party_payments_isa => SU.To_Unbounded_String("DWP third party payments - ISA"),
       dwp_third_party_payments_jsa => SU.To_Unbounded_String("DWP third party payments - JSA"),
       hb_only_or_separately => SU.To_Unbounded_String("HB only or separately"),
       ctb_only_or_separately => SU.To_Unbounded_String("CTB only or separately"),
       hb_ctb_paid_together => SU.To_Unbounded_String("HB/CTB paid together"),
       permanent_health_insurance => SU.To_Unbounded_String("Permanent health insurance"),
       any_other_sickness_insurance => SU.To_Unbounded_String("Any other sickness insurance"),
       critical_illness_cover => SU.To_Unbounded_String("Critical Illness Cover"),
       working_tax_credit => SU.To_Unbounded_String("Working Tax Credit"),
       child_tax_credit => SU.To_Unbounded_String("Child Tax Credit"),
       working_tax_credit_lump_sum => SU.To_Unbounded_String("Working Tax Credit Lump Sum"),
       child_tax_credit_lump_sum => SU.To_Unbounded_String("Child Tax Credit Lump Sum")
   );
end test_enum;












